export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const SWIPE_REQUEST = 'SWIPE_REQUEST';
export const SWIPE_SUCCESS = 'SWIPE_SUCCESS';
export const SWIPE_ERROR = 'SWIPE_ERROR';

export const TODAY_REQUEST = 'TODAY_REQUEST';
export const TODAY_SUCCESS = 'TODAY_SUCCESS';
export const TODAY_ERROR = 'TODAY_ERROR';

export const USER_MONTH_REQUEST = 'USER_MONTH_REQUEST';
export const USER_MONTH_SUCCESS = 'USER_MONTH_SUCCESS';
export const USER_MONTH_ERROR = 'USER_MONTH_ERROR';